# Generated by Django 5.2.4 on 2025-07-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "gas_types",
                    models.CharField(help_text="Types de gaz détectés", max_length=200),
                ),
                (
                    "sensor_types",
                    models.CharField(help_text="Types de capteurs", max_length=200),
                ),
            ],
        ),
    ]
