# Generated by Django 5.2.4 on 2025-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="end_of_life_date",
            field=models.DateField(
                blank=True, help_text="Fin de vie (obsolescence)", null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="warranty_end_date",
            field=models.DateField(blank=True, help_text="Fin de garantie", null=True),
        ),
    ]
